### ISSUE TITLE
References on calibration

### ISSUE THREAD

**Issue by jhnsnshen** [richards-tech/RTIMULib2#5]
hi, first thanks for the useful lib.
Since I could like to learn more about the process of calibration, so could you please list some references on calibraion of the sensor ?
Many thanks!

**Comment by r-b-us** [comment]
How about this - https://github.com/kriswiner/MPU-6050/wiki/Simple-and-Effective-Magnetometer-Calibration

**Comment by jhnsnshen** [comment]
Get it.
Thanks for the reply.
